title = "Portfolio Website"
baseURL = "https://github.com/sidharth256/portfolio.github.io"
languageCode = "en-us"
theme = "ananke"
resourceDir = "../resources"

DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 10 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true
canonifyURLs = true

[languages]
  [languages.en]
    title = "HOME"
    weight = 4
    contentDir = "content/en"
    # languageDirection = 'rtl' for Right-To-Left languages


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  text_color = "black"
  author = ""
  favicon = ""
  site_logo = ""
  #description = "The last theme you'll ever need. Maybe."
  # choose a background color from any on this page: https://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-black"
  recent_posts_number = 3


[[params.ananke_socials]]
name = "facebook"
url = "https://facebook.com/Sidhharth_K"

[[params.ananke_socials]]
name = "instagram"
url = "https://instagram.com/sidharth_k_25"



